# Vector

cukup menggunakan library numpy sahaja

In [1]:
import numpy as np

Vector in physics : quantity with value and magnitude

Vector in CS and Data Science: values that represent observations/predictions. or simply, vector is a list of numbers



In [3]:
# example of vector
v1 = np.array([1, 2, 3])
print(v)

[1 2 3]


In [5]:
v2 = np.array([4,5,6])

v1 + v2  # menjumlahkan 2 vektor

array([5, 7, 9])

akses elemen

In [8]:
print(v1[1])
print(v1[-1])

2
3


Vector norm : magnitude of a vector. atau panjangnya

the computational thinking:

    norm = 0

    for i in range ( len(vector)):

        norm=0

        norm+= vector[l] **2
    
    norm=sqrt(norm)

In [10]:
v3 = np.array([6,8])
v3_norm = np.linalg.norm(v3)

print(v3_norm)

10.0


In [9]:
v1_norm = np.linalg.norm(v1)
print(v1_norm)

3.7416573867739413


In [11]:
# dengan Manhattam distance
v3_norm = np.linalg.norm(v3, 1) #defaultnya 2 -> Euclidean
print(v3_norm)

14.0


### Arithmetic operations

#### Penjumlahan

In [12]:
print(v1, v2)

[1 2 3] [4 5 6]


In [26]:
v1 + 10   # penjumlahan skalar

array([11, 12, 13])

In [14]:
v1 + v2  # penjumlahan vector dengan vector

array([5, 7, 9])

In [15]:
v3 = np.array([2,5,6,1,3])

In [17]:
v1 + v3  # penjumlahan vektor hanya boleh dengan vektor berukuran sama

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

#### Pengurangan

In [18]:
v1 - 10  # pengurangan skalar

array([-9, -8, -7])

In [19]:
10 - v1

array([9, 8, 7])

In [25]:
v1 - v2  # vektor - vektor

array([-3, -3, -3])

#### Pembagian

In [21]:
print(v1, v2)

[1 2 3] [4 5 6]


In [24]:
v1 / 2  # pembagian dengan skalar

array([0.5, 1. , 1.5])

In [27]:
v2 / v1  # pembagian vektor dengan vektor

array([4. , 2.5, 2. ])

#### Perkalian

3 ways: scalar, vector, dot product

In [28]:
v1 * 10  # perkalian dengan skalar

array([10, 20, 30])

In [29]:
v1 * v2  # perkalian dengan vektor (element-wise)

array([ 4, 10, 18])

Result of dot product is a scalar.

In [30]:
v1 @ v2 # perkalian dot product

32

In [31]:
np.dot(v1, v2) # dot product with numpy

32

In [32]:
v1.dot(v2) # penulisan lain

32

formula tambahan terkait dot product:

vektor(a) @ vektor(b) = norm(a) * norm(b) * cos(theta)

#### Cosine similarity

In [33]:
print(v1, v2)

[1 2 3] [4 5 6]


In [35]:
cos_theta = v1 @ v2 / (np.linalg.norm(v1) * np.linalg.norm(v2))
cos_theta

0.9746318461970762

In [37]:
# contoh lain dengan 2 vektor yang saling berhimpit (theta = 0)
u1 = np.array([5,0])
u2 = np.array([8,0])
cos_theta = u1 @ u2 / (np.linalg.norm(u1) * np.linalg.norm(u2))
cos_theta

1.0

Umumnya:

0,5 < cos_theta < 1     artinya tingkat kemiripan tinggi

0 < cos_theta < 0,5     artinya tingkat kemiripan rendah

#### Implementasi cosine similarity

* kalimat 1 = saya pergi ke rumah nenek saya
* kalimat 2 = sata pergi ke rumah kakek saya

convert tiap kalimat menjadi list, dengan cara cek unique valuenya.

daftar unique value = saya, pergi, ke, rumah, nenek, kakek

In [38]:
k1 = [2,1,1,1,1,0]
k2 = [2,1,1,1,0,1]

k1 = np.array(k1)
k2 = np.array(k2)

print(k1, k2)

[2 1 1 1 1 0] [2 1 1 1 0 1]


cek dengan cosine similarity

In [39]:
cos_theta = k1 @ k2 / (np.linalg.norm(k1) * np.linalg.norm(k2))
cos_theta

0.8749999999999998

maka kedua kalimat bisa dikatakan memiliki tingkat kemiripan yang tinggi

Contoh 2:
* kalimat 1 = kemarin saya pergi ke surabaya
* kalimat 2 = ibu saya sedang berbelanja

unique val = kemarin, saya, pergi, ke, surabaya, ibu, sedang, berbelanja

In [40]:
ka1 = [1,1,1,1,1,0,0,0]
ka2 = [0,1,0,0,0,1,1,1]

ka1 = np.array(ka1)
ka2 = np.array(ka2)

print(ka1, ka2)

[1 1 1 1 1 0 0 0] [0 1 0 0 0 1 1 1]


In [41]:
cos_theta = ka1 @ ka2 / (np.linalg.norm(ka1) * np.linalg.norm(ka2))
cos_theta

0.22360679774997896

tingkat kemiripan kedua kalimat tersebut rendah

Contoh 3:
* kalimat 1 = saya makan ikan
* kalimat 2 = ikan makan saya

unique = saya, makan, ikan

In [42]:
ka3 = [1,1,1]
ka4 = [1,1,1]

ka3 = np.array(ka3)
ka4 = np.array(ka4)

print(ka3, ka4)

[1 1 1] [1 1 1]


In [43]:
cos_theta = ka3 @ ka4 / (np.linalg.norm(ka3) * np.linalg.norm(ka4))
cos_theta

1.0000000000000002

ternyata kemiripan tinggi, padahal kedua kalimat tersebut memiliki arti yang sangat berbeda. 

Ini merupakan salah satu kekurangan cosine similarity

Cara mencari degree/theta:

In [52]:
u1 = np.array([5,0])
u2 = np.array([0,8])
cos_theta = u1 @ u2 / (np.linalg.norm(u1) * np.linalg.norm(u2))
cos_theta

0.0

In [53]:
rad = np.arccos(cos_theta) #convert ke radian
rad 

1.5707963267948966

In [55]:
deg = np.degrees(rad)  # convert ke degree
deg

90.0

kesimpulan : 

cos(theta) = 0 , maka theta = 90 derajat