In [3]:
import numpy as np

# Matrix  
a 2-D array that consists of row and column

In [4]:
# Matrix in python

A = [[1,2], [2,3], [3,4]]
np.array(A)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [6]:
B = np.array([[1,2], [2,3], [3,4]])  # another way
B

array([[1, 2],
       [2, 3],
       [3, 4]])

Dimensi bisa dilihat dari 2 POV:
* Array/Data
* Representasi Data -> jumlah kolom

Types of Matrix:
* Square matrix  -> X = `array`([4,9,2], [3,5,7], [8,1,6])
* Upper triangle matrix  -> `np.triu(X)`
* Lower triangle matrix  -> `np.tril(X)`
* Diagonal matrix  -> `np.diag(X)`
* Identity matrix  -> `np.eye(shape)`

matrix dikali (@) dengan identity matrix hasilnya adalah matrix itu sendiri

matrix dikalikan dengan ***inverse*** hasilnya adalah matrix identitas

A @ A^-1 = I

#### Akses elemen di matrix

In [8]:
A = np.array([  [1,2,3],
                [4,5,6],
                [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
A[1]

array([4, 5, 6])

In [10]:
A[1][2]

6

In [11]:
A[1,2]

6

In [12]:
A[:,2] # akses kolom terakhir

array([3, 6, 9])

In [13]:
np.diag(A)

array([1, 5, 9])

In [14]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Arithmetic operations

In [18]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
B = np.array([ [1,2,0],
                [4,1,3],
                [2,5,0]])
B

array([[1, 2, 0],
       [4, 1, 3],
       [2, 5, 0]])

Penjumlahan

In [20]:
A + B

array([[ 2,  4,  3],
       [ 8,  6,  9],
       [ 9, 13,  9]])

In [21]:
10 + A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

Pengurangan

In [23]:
A - B

array([[0, 0, 3],
       [0, 4, 3],
       [5, 3, 9]])

In [24]:
10 - A

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [25]:
A - 10

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

Pembagian

In [27]:
B / A

array([[1.        , 1.        , 0.        ],
       [1.        , 0.2       , 0.5       ],
       [0.28571429, 0.625     , 0.        ]])

Perkalian : matrix-scalar, matrix-matrix, hadamard product

In [30]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
A * 10  # matrix-scalar

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
A * np.eye(3)   # hadamard product. ini gak ikut aturan linear algebra

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

hadamard product : performed element-wise. Bukan yang berdasarkan linear algebra

rules for matrix-matrix:
* number of columns in 1st matrix must equal the number of rows in 2nd matrix.  

    A(m,k) @ B(k,n) = C(m,n)

* cara pengisian matrix hasil = baris 1st matrix dikali kolom 2nd matrix 

    dot product baris 1st matrix dengan kolom 2nd matrix

In [36]:
J = np.array([  [1,2,0],
                [0,3,1],
                [1,0,0]])
K = np.array([  [0,1],
                [1,2],
                [0,1]])

In [33]:
J

array([[1, 2, 0],
       [0, 3, 1],
       [1, 0, 0]])

In [34]:
K

array([[0, 1],
       [1, 2],
       [0, 1]])

In [35]:
J @ K  # matrix-matrix. ikut linear algebra

array([[2, 5],
       [3, 7],
       [0, 1]])

Transpose

* row -> column
* column -> row

In [37]:
J

array([[1, 2, 0],
       [0, 3, 1],
       [1, 0, 0]])

In [38]:
J.T

array([[1, 0, 1],
       [2, 3, 0],
       [0, 1, 0]])

In [42]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Inverse

In [44]:
inv_J = np.linalg.inv(J)
inv_J

array([[ 0. ,  0. ,  1. ],
       [ 0.5,  0. , -0.5],
       [-1.5,  1. ,  1.5]])

In [46]:
J @ inv_J  # matrix dikali matrix inversenya = matrix identitas

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
inv_B = np.linalg.inv(B)
inv_B

array([[ 5.        ,  0.        , -2.        ],
       [-2.        ,  0.        ,  1.        ],
       [-6.        ,  0.33333333,  2.33333333]])

In [47]:
B @ inv_B

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 0.0000000e+00, 1.0000000e+00]])

In [50]:
inv_A = np.linalg.inv(A)
inv_A

LinAlgError: Singular matrix

singular matrix ga punya inverse

In [51]:
np.linalg.det(A)

0.0

determinan = o maka pasti ga punya inverse

# Tensor
is a generalization of vectors and matrices and is easily understood as a multidimensional array. 

A vector is a one-dimensional or first order tensor and 

a matrix is a two-dimensional or second order tensor

In [52]:
X = np.array([  [1,5,1,3],
                [3,7,2,1]])
Y = np.array([  [5,1,2,5],
                [5,1,0,0]])
Z = np.array([  [0,6,1,0],
                [3,1,0,0]])

In [53]:
X.shape

(2, 4)

In [54]:
tensor = np.array([X,Y,Z])
tensor

array([[[1, 5, 1, 3],
        [3, 7, 2, 1]],

       [[5, 1, 2, 5],
        [5, 1, 0, 0]],

       [[0, 6, 1, 0],
        [3, 1, 0, 0]]])

In [55]:
tensor.shape

(3, 2, 4)

shape (3, 2, 4) artinya 
* 3 -> jumlah matrix
* 2 -> masing2 matrix punya 2 baris
* 4 -> masing2 matrix punya 4 kolom