In [1]:
import numpy as np

# Eigen

brief linear transformation

T: **V** -> **W** ; T(*v*) = *w*

*v* = vektor awal

*w* = vektor akhir

In [2]:
A = np.array([  [1,2,3],
                [4,5,6],
                [7,8,9]])

In [5]:
np.linalg.eig(A)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [6]:
values, vector = np.linalg.eig(A)
print(values)
print(vector)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


eigen value berbentuk vektor. karena dikalikan vektor unit.

vector unit = magnitude 1

In [7]:
B = np.array([  [1,2],
                [2,4]])
B

array([[1, 2],
       [2, 4]])

In [8]:
values, vector = np.linalg.eig(B)
print(values)
print(vector)

[0. 5.]
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


reconstruct

In [9]:
values

array([0., 5.])

In [10]:
vector

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [11]:
recon = vector @ np.diag(values) @ np.linalg.inv(vector)
recon

array([[1., 2.],
       [2., 4.]])

dia balik ke version awal matriks B

Moreover:

In [14]:
C = np.array([[0, -1], [1,0]])
C

array([[ 0, -1],
       [ 1,  0]])

In [15]:
values, vector = np.linalg.eig(C)
print(values)
print(vector)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [16]:
print(abs(values))

[1. 1.]


In [17]:
print(abs(vector))

[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


## Case study: social media analysis

Ada 6 akun di twitter, 1 circle. 
* A diRT C, D           --(2 orang)
* B diRT A, C, D, E     --(4 orang)
* C diRT no one         --(0 orang)
* D diRT A, E           --(2 orang)
* E diRT no one         --(0 orang)
* F diRT C, D           --(2 orang)

In [18]:
sc = np.array([ [0, .25, 0, .5, 0, 0],
                [0,0,0,0,0,0],
                [.5, .25, 0, 0, 0, .5],
                [.5, .25, 0, 0, 0, .5],
                [0, .25, 0, .5, 0, 0],
                [0,0,0,0,0,0]])
sc

array([[0.  , 0.25, 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.25, 0.  , 0.  , 0.  , 0.5 ],
       [0.5 , 0.25, 0.  , 0.  , 0.  , 0.5 ],
       [0.  , 0.25, 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

siapa paling populer?

In [20]:
# cari eig val and vector
e_val, e_vec = np.linalg.eig(sc)
print(e_val)
print(e_vec)

[ 0.   0.   0.5 -0.5  0.   0. ]
[[ 0.00000000e+000  0.00000000e+000  5.00000000e-001 -5.00000000e-001
  -2.16623325e-276 -2.34960985e-276]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   4.33246650e-276  0.00000000e+000]
 [ 0.00000000e+000  1.00000000e+000  5.00000000e-001  5.00000000e-001
   6.00000000e-001  2.16930458e-001]
 [ 0.00000000e+000  0.00000000e+000  5.00000000e-001  5.00000000e-001
  -2.16623325e-276  1.10526918e-291]
 [ 1.00000000e+000  0.00000000e+000  5.00000000e-001 -5.00000000e-001
  -8.00000000e-001 -9.76187060e-001]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  2.34960985e-276]]


In [21]:
# cari posisi eig value terbesar
np.argmax(e_val)

2

eigen value terbesar ada di index = 2

In [22]:
# dari pasangan eig val terbesar, cari posisi nilai terbesar di dalam eig vectornya
e_vec[2]

array([0.        , 1.        , 0.5       , 0.5       , 0.6       ,
       0.21693046])

di atas adalah nilai2 di index 2. posisinya?

In [23]:
np.argmax(e_vec[2])

1

artinya posisi ke-1 atau akun B memiliki pengaruh besar di lingkup pergaulannya (paling banyak diRT)

menentukan orang paling berpengaruh ke-dua gimana? take out si B lalu dihitung ulang