In [1]:
import numpy as np

## 1. Buatlah tensor di bawah ini 

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \ 99 & 43 \end{bmatrix} \ \begin{bmatrix} 75 & 21 \ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \ 18 & 84 \end{bmatrix} \end{bmatrix} $$

Jawaban:

In [3]:
a = np.array([[23, 50], [7, 12]])
a

array([[23, 50],
       [ 7, 12]])

In [4]:
b = np.array([[75, 21], [57, 12]])
c = np.array([[57, 67], [99, 43]])
d = np.array([[87, 26], [18, 84]])

In [11]:
tensor = np.array([a, b, c, d])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[75, 21],
        [57, 12]],

       [[57, 67],
        [99, 43]],

       [[87, 26],
        [18, 84]]])

In [12]:
tensor.shape

(4, 2, 2)

## 2. Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$

Jawaban:

In [13]:
A = np.array([
                [23, 50, 19],
                [7, 12, 109],
                [57, 67, 98]
])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [15]:
B = np.array([[17], [22],[19]])
B

array([[17],
       [22],
       [19]])

In [16]:
A @ B  #matrix-matrix

array([[1852],
       [2454],
       [4305]])

In [17]:
A * B  # hadamard product

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

## 3. Lakukan transpose, hitung determinan, dan inverse terhadap matrix di bawah:

$$ \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} $$

In [18]:
A = np.array([
                [23, 50, 19],
                [7, 12, 109],
                [57, 67, 98]
])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

Transpose:

In [19]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

Determinan:

In [20]:
np.linalg.det(A)

131344.0000000002

Inverse:

In [21]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])