# NUMPY

#### Terminology

shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. 

A 2D array that looks like this:

```py
[[0., 0., 0.],
 [1., 1., 1.]]
```
means your array has 2 axes. First has a length of 2 and second has length of 3.

#### Creating Array

```py
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()
```

In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
# empty function creates an array whose initial content is random and depends on the state of the memory
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
# array with a range of elements

print(np.arange(4))
print(np.arange(0,9,3))  #start, stop, step

[0 1 2 3]
[0 3 6]


### List vs NumPy

In [12]:
height = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
weight = [60.5, 61.5, 62.5, 63.5, 64.5, 65.5]

#BMI
weight/height **2  #output error karena cuma pake List

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
import numpy as np
height = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
weight = [60.5, 61.5, 62.5, 63.5, 64.5, 65.5]
np_height = np.array(height)
np_weight = np.array(weight)

np_weight/np_height **2  # no error karena udah pake NumPy

array([20.93425606, 18.98148148, 17.31301939, 52.47933884, 52.34964694,
       52.21619898])

### Add, Remove, and Sort
```py
np.append()
np.delete()
np.sort()
```

In [14]:
arr=np.array([1,2,3,4,5,6,7,8])

arr1=np.append(arr,[9, 10, 11])

print(arr)
print(arr1)

[1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10 11]


In [15]:
np.delete(arr, 1) # delete element in position 1 of array

array([1, 3, 4, 5, 6, 7, 8])

In [17]:
array_rando = np.array([2,5,7,3,1,9])
np.sort(array_rando) # sort the numbers in ascending order

array([1, 2, 3, 5, 7, 9])

### Shape and Size

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2D array with 2 rows and 3 columns, the shape of your array is (2,3).

In [2]:
example = np.array([[[0, 1, 2, 3],
                        [4, 5, 6, 7]],

                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],

                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]]])
print(example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [22]:
example.ndim

3

In [23]:
example.size

24

In [24]:
example.shape

(3, 2, 4)

### Reshape

`np.reshape()`  will give a new shape without changing the data.

caution: the new array needs to have the same number of elements as the original array

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
# reshaping into an array with 3 rows and 2 columns

b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [27]:
a.reshape(6,1)  # 6 rows and 1 column

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

`np.reshape()` can specify a few optional parameters:

`np.reshape(a, newshape, order)`
* `a` is the array to be reshaped
* `newshape` is the new shape. Can specify integer or tuple of integers.
* `order` 'C' = read/write the elements using C-like index order, 'F' = Fortran-like index order, 'A' = ???

# Convert 1D to 2D

`np.newaxis` increase dimension by 1 dimension (1D become 2D)

`np.expand_dims`

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [10]:
a2 = a[np.newaxis]  # adding new axis to a
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [11]:
row_vector = a[np.newaxis, :] # convert 1D array to a row vector by inserting an axis along the 1st dimension
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [12]:
col_vector = a[:, np.newaxis] # convert 1D array to a column vector
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [15]:
# EXPAND_DIMS

a = np.array([1, 2, 3, 4, 5, 6])  #starting array
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


In [16]:
b = np.expand_dims(a, axis=1)  #adding an axis at index position 1
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [17]:
c = np.expand_dims(a, axis=0)  #adding an axis at index position 0
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


### Indexing and Slicing

In [18]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


selecting values from array that fulfill certain conditions

In [19]:
# starting array
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
print(a[a>=5])  #printing all values which >= 5

[ 5  6  7  8  9 10 11 12]


In [21]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [30]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print('\n',c)

[ 2  4  6  8 10 12]

 [ 3  4  5  6  7  8  9 10]


### Creating Array from existing data
* slicing indexing
* np.vstack()
* np.hstack()
* np.hsplit()
* .view()
* .copy()

In [31]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])  # starting array

arr1 = arr[3:8]  # new array made by slicing arr
arr1

array([4, 5, 6, 7, 8])

In [32]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])
np.vstack((a_1, a_2))    # stacking array a_1 and a_2 vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [33]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [34]:
np.hsplit(arrsplit,3)  # splitting arrsplit horizontally into 3 equally shaped array

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [35]:
b = a.view()  # create a new array object that LOOKS at the same data
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
c = a.copy()  # a complete copy (A DEEP COPY)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operations

In [ ]:
...

### Zero dimension / scalar

### 1 D / vector

### 2 D / matrix

In [36]:
arr=np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
arr.ndim

2

In [35]:
arr.shape

(2, 4)

In [38]:
arr.size

8

#### more

In [42]:
np.arange(3, 5)  # how??

array([3, 4])

In [44]:
arr_2d=np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [46]:
arr_2d.shape

(2, 4)

In [53]:
a2=np.expand_dims(arr_2d, axis=0)
a2.shape

(1, 2, 4)

#### soal

In [38]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[2:7])
print(arr[:8:3])

[ 7  4 10  5 13]
[ 1  4 13]


In [41]:
arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[0,2])
print(arr[1,2])

3
7


In [64]:
print(arr[0,1:3])
print(arr[1,2:4])
print(arr[0,2:3])

[2 3]
[7 8]
[3]


In [42]:
print(arr[2:4,2])
print(arr[2:3,3])
print(arr[1:3,2])
print(arr[2:4,2])

[11]
[12]
[ 7 11]
[11]


In [72]:
arr=np.array([[1,2,3,4, 8, 10], [5,6,7,8, 7, 10], [9,10,11,12, 11, 12]])
print(arr[:4:2,2])
print(arr[1:2,2:3])
print(arr[1:2,2:4])
print(arr[1:3,2:4])

[ 3 11]
[[7]]
[[7 8]]
[[ 7  8]
 [11 12]]


### latihan

In [73]:
print(arr[arr>=3])

[ 3  4  8 10  5  6  7  8  7 10  9 10 11 12 11 12]


#### moreover

In [79]:
a_1 = np.array([[1,1], 
                [2,2]])
a_2 = np.array([[3,3], 
                [4,4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [78]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [82]:
arr_new1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr_new2 = arr_new1.reshape(2,3,2)
print(arr_new2.shape)
print(arr_new2)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [85]:
arr_new3 = arr_new1.reshape(2,3,-1) # unkown dimension
print(arr_new3.shape)
print(arr_new3)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [88]:
arr_new4 = arr_new1.reshape(2,2,3) # unkown dimension
print(arr_new4.shape)
print(arr_new4)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
