# FUNCTION
You can define functions to provide the required functionality. Here are simple rules to define a function in Python.

* Function blocks begin with the keyword `def` followed by the function name and parentheses ( `( )` ).
* Any input parameters or arguments should be placed within these parentheses. You can also define parameters inside these parentheses.
* The first statement of a function can be an optional statement - the documentation string of the function or docstring.
* The code block within every function starts with a colon (`:`) and is indented.
* The statement return `[expression]` exits a function, optionally passing back an expression to the caller. A return statement with no arguments is the same as return None

In [1]:
# The syntax

def function_name (parameter):
    'docstring'
    statement(s)

In [5]:
def printme(str_input):
    '''this prints a passed string into this function'''
    print(str_input)

printme('first sentence')
printme('second sentence')

first sentence
second sentence


### Pass by reference vs value

In [96]:
def replaceme(mylist):
    mylist=mylist+[1,2,3,4]
    print('\nValues inside function : ', mylist)
    return mylist

mylist=[100,200,300]
print('\nValues outside the function - before : ', mylist)
mylist=replaceme(mylist)
print('Values outside the function - after : ', mylist)


Values outside the function - before :  [100, 200, 300]

Values inside function :  [100, 200, 300, 1, 2, 3, 4]
Values outside the function - after :  [100, 200, 300, 1, 2, 3, 4]


### Function Arguments

You can call a function by using the following types of formal arguments −

- Required arguments
- Keyword arguments
- Default arguments
- Variable-length arguments

1. Required argument

the arguments passed to a function in correct positional order. Here, the number of arguments in the function call should match exactly with the function definition

In [91]:
# example 1
def perin(input):
    print(input)

print('example #1')
perin('Hei 1')

# example 2
def cal_rect (length, width):
    print('Area = ', length*width)

length = 5
width = 7

print('\nexample #2')
cal_rect(length, width)

example #1
Hei 1

example #2
Area =  35


2. Keyword arguments

are related to the function calls. When you use keyword arguments in a function call, the caller identifies the arguments by the parameter name.

allows skip arguments or place them out of order.

In [92]:
def printer(input):
    print(input)

printer(input = 'hahachoo')

hahachoo


In [93]:
def printinfo(name, age):
    print('Name = ', name)
    print('Age = ', age)

printinfo(age=4, name='bbb')

Name =  bbb
Age =  4


3. Default argument

an argument that assumes a default value if a value is not provided in the function call for that argument.

In [95]:
def printinfo(name, age = 16):
    print('Name = ', name)
    print('Age = ', age)
    print('')

printinfo(age=40, name='ccc')
printinfo(name='ddd')

Name =  ccc
Age =  40

Name =  ddd
Age =  16



In [ ]:
# restriction: must write default-arg *after* required-arg

# example:
# def printinfo(name, age=22):

# NOT like this:
# def printinfo(age=26, name):

4. Variable-length arguments

You may need to process a function for more arguments than you specified while defining the function. These arguments are called variable-length arguments and are not named in the function definition, unlike required and default arguments.

In [ ]:
# JARANG DIGUNAKAN

#### Return vs no return

In [12]:
def area(alas, tinggi):
    luas = alas * tinggi
    return luas    # pake return

area(2,3)

6

In [13]:
def area1(alas, tinggi):
    luas = alas * tinggi
                            #ga pake return = no output
area1(2,3)

In [19]:
def area3(alas, tinggi):
    luas = alas * tinggi
    luas2 = alas * 2
    return luas, luas2    

print(area3(2,3))
print(area3(2,3)[0])
print(area3(2,3)[1])

(6, 4)
6
4


In [20]:
# Function definition is here
def changeme( mylist ):
   '''This changes a passed list into this function'''
   mylist = [1, 2, 3, 4] # This would assign new reference in mylist
   print("Values inside the function  : ", mylist)

# Now you can call changeme function
mylist = [10, 20, 30]
changeme( mylist )
print("Values outside the function : ", mylist)

Values inside the function  :  [1, 2, 3, 4]
Values outside the function :  [10, 20, 30]


In [28]:
sum = lambda arg1, arg2 : arg1 + arg2 

print(sum(1,3))

4


In [29]:
tambah = 1
tambah = lambda arg1, arg2 : arg1+arg2

print('before', tambah)
tambah(5,2)
print('after',tambah)

before <function <lambda> at 0x000002A42E226940>
after <function <lambda> at 0x000002A42E226940>


# Module n Package

In [14]:
import person as ps
print(ps.name)
print(ps)
print(ps.devices)
print(ps.devices[0:2])
ps.display('ahah')
ps.display(ahah)

zack
<module 'person' from 'c:\\Users\\Naufal\\Documents\\hacktiv8\\learning_journal\\phase_0\\week_1\\person.py'>
['laptop', 'smartphone', 'tablet']
['laptop', 'smartphone']
arg = ahah


NameError: name 'ahah' is not defined

# NUMPY

In [20]:
import numpy as np

In [ ]:
height = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
weight = [60.5, 61.5, 62.5, 63.5, 64.5, 65.5]

In [21]:
np.arange(5) # array range?

array([0, 1, 2, 3, 4])

In [28]:
arr=np.array([1,2,3,4])
arr_new=np.append(arr,[9, 10, 11])

print(arr)
print(arr_new)
np.delete(arr_new,3)

[1 2 3 4]
[ 1  2  3  4  9 10 11]


array([ 1,  2,  3,  9, 10, 11])

### Zero dimension / scalar

### 1 D / vector

### 2 D / matrix

In [36]:
arr=np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
arr.ndim

2

In [35]:
arr.shape

(2, 4)

In [38]:
arr.size

8

#### more

In [42]:
np.arange(3, 5)  # how??

array([3, 4])

In [44]:
arr_2d=np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [46]:
arr_2d.shape

(2, 4)

In [53]:
a2=np.expand_dims(arr_2d, axis=0)
a2.shape

(1, 2, 4)

#### soal

In [59]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[2:7])
print(arr[:8:3])

[ 7  4 10  5 13]
[ 1  4 13]


In [61]:
arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[0,2])
print(arr[1,2])

3
7


In [64]:
print(arr[0,1:3])
print(arr[1,2:4])
print(arr[0,2:3])

[2 3]
[7 8]
[3]


In [68]:
print(arr[2:4,2])
print(arr[2:3,3])
print(arr[1:3,2])
print(arr[2:4,4])

[11]
[12]
[ 7 11]


IndexError: index 4 is out of bounds for axis 1 with size 4

In [72]:
arr=np.array([[1,2,3,4, 8, 10], [5,6,7,8, 7, 10], [9,10,11,12, 11, 12]])
print(arr[:4:2,2])
print(arr[1:2,2:3])
print(arr[1:2,2:4])
print(arr[1:3,2:4])

[ 3 11]
[[7]]
[[7 8]]
[[ 7  8]
 [11 12]]


### latihan

In [73]:
print(arr[arr>=3])

[ 3  4  8 10  5  6  7  8  7 10  9 10 11 12 11 12]


#### moreover

In [79]:
a_1 = np.array([[1,1], 
                [2,2]])
a_2 = np.array([[3,3], 
                [4,4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [78]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [82]:
arr_new1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr_new2 = arr_new1.reshape(2,3,2)
print(arr_new2.shape)
print(arr_new2)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [85]:
arr_new3 = arr_new1.reshape(2,3,-1) # unkown dimension
print(arr_new3.shape)
print(arr_new3)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [88]:
arr_new4 = arr_new1.reshape(2,2,3) # unkown dimension
print(arr_new4.shape)
print(arr_new4)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
